### ISSUE TITLE
Downgrade "easyrdf/easyrdf": "0.10.0-alpha.1 as 0.9.1" to not use an alias?

### ISSUE THREAD

**Issue by verbruggenalex** [openeuropa/oe_content#158]
Issue already reported here: https://github.com/openeuropa/oe_content/issues/77

When trying to build an openeuropa/distribution kind of package we found that using the alias approach here can only be used in the root composer.json and not in the composer.json of a dependency of the root project:

https://github.com/verbruggenalex/oesd/blob/master/composer.json#L22

Can anyone tell me why it is not possible to use the same version as drupal core requires?
`- drupal/core 8.7.0 requires easyrdf/easyrdf ^0.9 -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.0-rc.1, 0.9.0-rc.2, 0.9.0-rc.3, 0.9.0-rc.4, 0.9.0-rc.5, 0.9.1, 0.9.x-dev].`

Simply running `composer require openeuropa/oe_theme` does NOT work. The absolute minimum that should happen is to document that if someone wants to install the package that they should copy the aliased package into their own require section.

**Comment by brummbar** [comment]
The version 0.10.0-alpha.1 is required by the rdf_entity module. The version includes fixes that are required for the module functionality. I'll open a ticket on our board to document this requirement.

Closing this issue as downgrading is obviously not possible.
