### ISSUE TITLE
Module drupal/typed_link is missing after installation

### ISSUE THREAD

**Issue by yenyasinn** [openeuropa/oe_content#206]
**Description**
Package drupal/typed_link is defined as a dependency of oe_content but this module is defined in require-dev section of composer.json and isn't installed for production sites

**Steps to reproduce**
Install project using  https://github.com/openeuropa/drupal-site-template.
Install oe_content module `composer require "openeuropa/oe_content":"^1.8"`.
Enable openeuropa/oe_content `drush en oe_content -y`

**Expected behavior:** Module oe_content is installed

**Actual behavior:** Error message: ` Unable to install modules: module 'oe_content' is missing its dependency module typed_link.`

**Versions**
openeuropa/drupal-site-template - 1.3.0, openeuropa/oe_content - 1.8.1

**Comment by brummbar** [comment]
This has been fixed.
