### ISSUE TITLE
Installation: conflict with drupal 8.9.7  - easyrdf

### ISSUE THREAD

**Issue by mirba** [openeuropa/oe_content#321]
When running  
`composer require openeuropa/oe_content`

Resulting error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: easyrdf/easyrdf[0.9.1, 0.10.0-alpha.1].
    - Can only install one of: easyrdf/easyrdf[0.10.0-alpha.1, 0.9.1].
    - Can only install one of: easyrdf/easyrdf[0.10.0-alpha.1, 0.9.1].
    - openeuropa/oe_content 1.11.0 requires easyrdf/easyrdf 0.10.0-alpha.1 as 0.9.1 -> satisfiable by easyrdf/easyrdf[0.10.0-alpha.1].
    - Installation request for openeuropa/oe_content ^1.11 -> satisfiable by openeuropa/oe_content[1.11.0].
    - Installation request for easyrdf/easyrdf (locked at 0.9.1) -> satisfiable by easyrdf/easyrdf[0.9.1].
```

**Comment by cmarcmar** [comment]
Hi,

I had the exact same issue and it has been fixed by adding this dependency to the composer.json file:
"easyrdf/easyrdf": "0.10.0-alpha.1 as 0.9.1"

Hope it helps!

**Comment by brummbar** [comment]
Marking it as solved.

**Comment by KostasBlank** [comment]
For version 2.x of oe_content use "easyrdf/easyrdf": "1.0.0 as 0.9.2" i.e:

1. In your composer.json add: "easyrdf/easyrdf": "1.0.0 as 0.9.2" 
2. Run: composer update easyrdf/easyrdf
3. Finally install using: composer require openeuropa/oe_content
