### ISSUE TITLE
Cannot apply patch https://www.drupal.org/project/inline_entity_form/issues/3162384 (https://www.drupal.org/files/issues/2020-08-13/fixed_duplicate_rows-3162384-16.patch)!

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_content#331]
In addition the ticket is closed as duplicated https://www.drupal.org/project/inline_entity_form/issues/3162384

and it was fixed here: https://www.drupal.org/project/inline_entity_form/issues/3121071

**Comment by LOBsTerr** [comment]
The second patch also can't be applied anymore
`
https://www.drupal.org/files/issues/2020-08-04/inline_entity_form-no_label_required_field_with_no_entries-2842744-27-D8.patch
`

**Comment by brummbar** [comment]
Patch was updated, thanks for reporting this.
