### ISSUE TITLE
Security warning for Remote Stream Wrapper dependency 

### ISSUE THREAD

**Issue by sotiropo** [openeuropa/oe_content#520]
Hello.
There is a security warning for drupal/remote_stream_wrapper:1.5 version, which is an internal dependency for openeuropa/oe_content. 
https://www.drupal.org/pift-ci-job/2220661 
What is your plan/advice for the required security update?

**Comment by nagyad** [comment]
The issue was resolved after remote_stream_wrapper had been fixed.
