### ISSUE TITLE
Issues with latest oe_content_social_media_links_field updates

### ISSUE THREAD

**Issue by ansergeyg** [openeuropa/oe_content#548]
Hi there,
We are using openeuropa module oe_content_social_media_links_field

and recently after updating our composer dependencies (oe_theme to the latest version, we don't use oe_content, but it's enabled on our website) we are facing issues with rebuilding our website.

Error:

`Unable to decode output into JSON: Syntax error
                                                                                                                                                                                      
  Error: Call to a member function get() on null in oe_content_social_media_links_field_post_update_00001() (line 15 of /home/sergey/web/ds/web/modules/contrib/oe_content/modules/o
  e_content_social_media_links_field/oe_content_social_media_links_field.post_update.php).`

The module page:
https://github.com/openeuropa/oe_content/tree/dda9e173f6bc305ce03d8c9c185645f7b069e490/modules/oe_content_social_media_links_field

We think that the update code:
https://github.com/openeuropa/oe_content/blob/dda9e173f6bc305ce03d8c9c185645f7b069e490/modules/oe_content_social_media_links_field/oe_content_social_media_links_field.post_update.php

is not sufficient because it implies that the client should have this field:

node.oe_social_media_links

but in fact, clients are not obliged to have this field.

But it's only our assumption.

Could you please clarify this issue?

Regards,Sergey

**Comment by nagyad** [comment]
Sorry for the late reply. We are working on it, son a PR will be opened.

**Comment by upchuk** [comment]
@ansergeyg hey there, we merged the fix for this issue.
