### ISSUE TITLE
Patches cannot be applied

### ISSUE THREAD

**Issue by ansergeyg** [openeuropa/oe_content#583]
Hi there,

After upgrading the module to the 3.0.0-alpha6 version we encountered the following issues:

`- Applying patches for drupal/inline_entity_form
    https://www.drupal.org/files/issues/2022-07-20/ief_removed_references_2875716-104.patch (https://www.drupal.org/project/inline_entity_form/issues/2875716)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2022-07-20/ief_removed_references_2875716-104.patch

`

and

`- Applying patches for drupal/typed_link
    https://www.drupal.org/files/issues/2022-02-09/typed_link_constraints-3263477-2.patch (https://www.drupal.org/project/typed_link/issues/3263477)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2022-02-09/typed_link_constraints-3263477-2.patch

`

Looks like both inline_entity_form and typed_link modules were updated including patches.

Regards, Sergey

**Comment by giucas-falchetto** [comment]
I confirm, both patches are now obsolete

**Comment by brummbar** [comment]
Patches were removed. Thanks for the report.
