### ISSUE TITLE
not forcing oe_documents widget to required

### ISSUE THREAD

**Issue by john4190** [openeuropa/oe_content#602]
I would strongly suggest you of commenting the row 36 of oe_content_publication.module. a publication file could be a paid one and this means a more appropriate solution in this case is exposing a link for buying it and obviously this means oe_documents field in this case cannot be mandatory

**Comment by brummbar** [comment]
Dear @john4190 , the content types in oe_content represent the vision of DG COMM. For your case, you can implement a form alter to remove the restriction provided by our module.
