### ISSUE TITLE
Patch cannot be applied after updating to Drupal 10.2

### ISSUE THREAD

**Issue by itzikas** [openeuropa/oe_content#606]
Hello everyone,

After updating to Drupal 10.2 the patch https://www.drupal.org/files/issues/2022-07-26/2230909-269.patch (https://www.drupal.org/project/drupal/issues/2230909) cannot be applied.

The patch which is successfully applied to this version is 
https://www.drupal.org/files/issues/2023-10-04/2230909-305.patch

Regards,
Giannis

**Comment by evonasek** [comment]
Could you please integrate this patch to composer.json?

**Comment by itzikas** [comment]
There is a new PR:

https://github.com/openeuropa/oe_content/pull/609

**Comment by nagyad** [comment]
Resolved by https://github.com/openeuropa/oe_content/pull/609
