### ISSUE TITLE
Problems with the easyrdf installation

### ISSUE THREAD

**Issue by davidjguru** [openeuropa/oe_content#77]
The line:  
"easyrdf/easyrdf": "0.10.0-alpha.1 as 0.9.1", It's causing installation problems inside the container just when try to install the oe_content module through Composer.

![Selection_025](https://user-images.githubusercontent.com/21089086/58418577-67639d80-8088-11e9-8b45-90e628c54073.png)

**Comment by haringsrob** [comment]
Hey @davidjguru,

I had a similar issue, you can work around this by doing the following:

1. in your composer.json add `"easyrdf/easyrdf": "0.10.0-alpha.1 as 0.9.1"`
2. run `composer update easyrdf/easyrdf`
3 finally install using `composer require openeuropa/oe_content`

**Comment by brummbar** [comment]
Thanks @haringsrob 👍
