### ISSUE TITLE
Problems using the field_group current version

### ISSUE THREAD

**Issue by davidjguru** [openeuropa/oe_content#95]
Hi, 
I was working in a issue in a openeuropa-based project, building a horizontal tabs layout when I thought about using a library of the field_group module, called "_field_group / formatter.horizontal_tabs_".  After some problems, I found some patches but they didn't apply because the version used in oe_content is "drupal/field_group": "^1.0".

Currently, oe_content is using https://www.drupal.org/project/field_group/releases/8.x-1.0, from november 2017, and so it is marked in his own composer.json. 

Would it be possible to update the dependency to a current version, type 3.0.0-rc1, for example?
Would there be many adaptation problems if the version is updated?
https://www.drupal.org/project/field_group/releases/8.x-3.0-rc1

Thanks in advance,

David.

**Comment by brummbar** [comment]
Hi @davidjguru , we are going to take a look at the upgrade in the upcoming week and see how much work it is.

**Comment by davidjguru** [comment]
Feedback received! 
Thanks a lot @brummbar  (in advance). 

Greetings.

**Comment by nagyad** [comment]
We have removed the dependency https://github.com/openeuropa/oe_content/pull/97/files. 
This will be in the next upcoming release. We have also contributed to an issue related to horizontal tabs on the module. https://www.drupal.org/project/field_group/issues/2787179 
We will reintroduce field_groups in an upcoming delivery for Event corporate content types.
